name: Build & push image for master

on:
  push:
    branches: ['master']

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build-and-push-image:
    name: Build and push Docker image
    uses: larsselbekk/github-actions/.github/workflows/build-and-push-image.yml@main
